In [ ]:
import numpy as np
a = np.array([1,2,3])


In [ ]:
a

array([1, 2, 3])

In [ ]:
b = np.array([4,6,3])


In [ ]:
b

array([4, 6, 3])

In [ ]:
c=a+b

In [ ]:
c

array([5, 8, 6])

In [ ]:
d =np.array([(1,2,3),(4,5,6)],dtype=float)


In [ ]:
d

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
e= d =np.array([(7,2,3),(4,20,6)],dtype=float)


In [ ]:
e

array([[ 7.,  2.,  3.],
       [ 4., 20.,  6.]])

In [ ]:
f=e+d

In [ ]:
f

array([[14.,  4.,  6.],
       [ 8., 40., 12.]])

In [ ]:
a.sort()

In [ ]:
a

array([1, 2, 3])

In [ ]:
a = np.array([11,2,33])


In [ ]:
a.sort()

In [ ]:
a

array([ 2, 11, 33])

In [20]:
d =np.array([(1,2,3),(4,5,6),(8,2,10),(42,50,6)],dtype=float)


In [21]:
d


array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 8.,  2., 10.],
       [42., 50.,  6.]])